version: "3.7"

services: 
    service:
        image: cart-service
        env_file: .env
        build: 
            target: builder
            context: .
        ports:
            - 18080:8080
        volumes: 
            - ./:/go/src/github.com/eduardohoraciosanto/bootcamp-with-gorilla
            - swagger:/go/src/github.com/eduardohoraciosanto/bootcamp-with-gorilla/swagger
            - ./oas/oas.yml:/go/src/github.com/eduardohoraciosanto/bootcamp-with-gorilla/swagger/swagger.yml
        command: gowatch
        depends_on: 
            - redis
            - swagger
    redis:
        image: redis
        restart: always
        ports: 
            - 16379:6379
    swagger:
        image: swaggerapi/swagger-ui:v3.23.10
        environment: 
            URL: /swagger/swagger.yml
        volumes: 
            - swagger:/usr/share/nginx/html
volumes: 
    #swagger named volume will be shared between service and swagger. So we can have a local swagger running
    swagger: